import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

function Home() {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <h1>Home Page</h1>
        <div>
          <Link href="/about" passHref>
            <button className={styles.button}>About</button>
          </Link>
          <Link href="/posts/" passHref>
            <button className={styles.button}>All Posts</button>
          </Link>
        </div>
      </div>
    </div>
  );
}

export default Home;
